version: "3.7"

networks:
  cluster-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.57.0/24
      

services:  
  redis-standalone:
    image: "redislabs/rejson:latest"    
    container_name: redis-standalone
    ports:
      - "6379"
    networks:
      cluster-network:
        ipv4_address: 192.168.57.17
  redis-master:
    image: "redislabs/rejson:latest"    
    container_name: redis-master    
    command: --port 6379 --loadmodule /usr/lib/redis/modules/redisai.so --loadmodule /usr/lib/redis/modules/redisearch.so --loadmodule /usr/lib/redis/modules/redisgraph.so --loadmodule /usr/lib/redis/modules/redistimeseries.so --loadmodule /usr/lib/redis/modules/rejson.so --loadmodule /usr/lib/redis/modules/redisbloom.so --loadmodule /var/opt/redislabs/lib/modules/redisgears.so Plugin /var/opt/redislabs/modules/rg/plugin/gears_python.so        
    ports:
      - "6379"
    networks:
      cluster-network:
        ipv4_address: 192.168.57.18
  redis-replica:
    image: "redislabs/rejson:latest"
    container_name: redis-replica
    command: --port 6379 --loadmodule /usr/lib/redis/modules/redisai.so --loadmodule /usr/lib/redis/modules/redisearch.so --loadmodule /usr/lib/redis/modules/redisgraph.so --loadmodule /usr/lib/redis/modules/redistimeseries.so --loadmodule /usr/lib/redis/modules/rejson.so --loadmodule /usr/lib/redis/modules/redisbloom.so --loadmodule /var/opt/redislabs/lib/modules/redisgears.so Plugin /var/opt/redislabs/modules/rg/plugin/gears_python.so --slaveof redis-master 6379
    ports:
      - "6379"
  redis-sentinel:    
    build:
      context: ./sentinel
    links:
      - redis-master
    ports:
      - "26379"
    networks:
      cluster-network:
        ipv4_address: 192.168.57.19
  redis-sentinel2:    
    build:
      context: ./sentinel
    links:
      - redis-master
    ports:
      - "26379"
    networks:
      cluster-network:
        ipv4_address: 192.168.57.20
  redis-sentinel3:    
    build:
      context: ./sentinel
    links:
      - redis-master
    ports:
      - "26379" 
    networks:
      cluster-network:
        ipv4_address: 192.168.57.21
  redis-cluster1:
    build:
      context: ./cluster
    ports:
      - '6379'
      - '16379'
    networks: 
      cluster-network:
        ipv4_address: 192.168.57.10
  redis-cluster2:
    build:
      context: ./cluster
    ports:
      - '6379'
      - '16379'
    networks:
      cluster-network:
        ipv4_address: 192.168.57.11
  redis-cluster3:
    build:
      context: ./cluster
    ports:
      - '6379'
      - '16379'
    networks:
      cluster-network:
        ipv4_address: 192.168.57.12
  redis-cluster4:
    build:
      context: ./cluster
    ports:
      - '6379'
      - '16379'
    networks:
      cluster-network:
        ipv4_address: 192.168.57.13
  redis-cluster5:
    build:
      context: ./cluster
    ports:
      - '6379'
      - '16379'
    networks:
      cluster-network:
        ipv4_address: 192.168.57.14
  redis-cluster6:
    build:
      context: ./cluster
    entrypoint: ["startup_cluster.sh"]
    ports:
      - '6379:6379'
      - '16379'
    networks:
      cluster-network:
        ipv4_address: 192.168.57.15
    depends_on: 
      - redis-cluster1
      - redis-cluster2
      - redis-cluster3
      - redis-cluster4
      - redis-cluster5
  dotnet:
    networks:
      cluster-network:
        ipv4_address: 192.168.57.16
    links:
      - redis-standalone      
      - redis-sentinel      
      - redis-cluster1
    environment:
      - STANDALONE_HOST_PORT=redis-standalone:6379
      - SENTINLE_HOST_PORT=redis-sentinel:26379
      - CLUSTER_HOST_PORT=redis-cluster1:6379
    build:
      context: ../
    depends_on:
      - redis-master
      - redis-replica
      - redis-sentinel
      - redis-sentinel2
      - redis-sentinel3
      - redis-standalone
      - redis-cluster1
      - redis-cluster2
      - redis-cluster3
      - redis-cluster4
      - redis-cluster5
      - redis-cluster6